from os import PathLike

__version__: str

class GxwError(Exception): ...
class FormatError(GxwError): ...
class UnsupportedFeatureError(GxwError): ...
class ResourceLimitError(GxwError): ...

class ReadLimits:
    def __init__(
        self,
        *,
        max_file_bytes: int = 67108864,
        max_stream_bytes: int = 67108864,
        max_total_stream_bytes: int = 268435456,
        max_entries: int = 65536,
        max_xml_bytes: int = 8388608,
        max_xml_depth: int = 64,
        max_xml_rows: int = 65536,
        max_tokens: int = 1000000,
    ) -> None: ...
    @property
    def max_file_bytes(self) -> int: ...
    @property
    def max_stream_bytes(self) -> int: ...
    @property
    def max_total_stream_bytes(self) -> int: ...
    @property
    def max_entries(self) -> int: ...
    @property
    def max_xml_bytes(self) -> int: ...
    @property
    def max_xml_depth(self) -> int: ...
    @property
    def max_xml_rows(self) -> int: ...
    @property
    def max_tokens(self) -> int: ...

class StreamInfo:
    @property
    def path(self) -> list[str]: ...
    @property
    def size(self) -> int: ...
    @property
    def sha256(self) -> str: ...

class ContainerIndex:
    @property
    def path(self) -> list[str]: ...
    @property
    def cfb_version(self) -> int: ...
    @property
    def streams(self) -> list[StreamInfo]: ...

class StreamLocation:
    @property
    def container(self) -> list[str]: ...
    @property
    def path(self) -> list[str]: ...

class MetadataRow:
    @property
    def fields(self) -> dict[str, str]: ...
    @property
    def attributes(self) -> dict[str, str]: ...
    @property
    def ancestors(self) -> list[str]: ...

class LogicalObject:
    @property
    def id(self) -> str | None: ...
    @property
    def logical_name(self) -> str | None: ...
    @property
    def scrap(self) -> bool | None: ...
    @property
    def historical(self) -> bool: ...
    @property
    def metadata(self) -> MetadataRow: ...
    @property
    def location(self) -> StreamLocation | None: ...

class Diagnostic:
    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def location(self) -> StreamLocation | None: ...

class ProjectIndex:
    @property
    def schema_version(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def sha256(self) -> str: ...
    @property
    def containers(self) -> list[ContainerIndex]: ...
    @property
    def logical_objects(self) -> list[LogicalObject]: ...
    @property
    def project_rows(self) -> list[MetadataRow]: ...
    @property
    def diagnostics(self) -> list[Diagnostic]: ...
    def to_json(self) -> str: ...

def inspect(path: str | PathLike[str], *, limits: ReadLimits | None = None) -> ProjectIndex: ...
def inspect_bytes(data: bytes, *, limits: ReadLimits | None = None) -> ProjectIndex: ...

class SourceSpan:
    @property
    def source_id(self) -> int: ...
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...

class SourceInfo:
    @property
    def source(self) -> SourceSpan: ...
    @property
    def id(self) -> int: ...
    @property
    def location(self) -> StreamLocation: ...
    @property
    def size(self) -> int: ...
    @property
    def sha256(self) -> str: ...

class ParseDiagnostic:
    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def source(self) -> SourceSpan | None: ...

class OpaqueRegion:
    @property
    def source(self) -> SourceSpan: ...
    @property
    def reason(self) -> str: ...

class RawToken:
    @property
    def ordinal(self) -> int: ...
    @property
    def source(self) -> SourceSpan: ...
    @property
    def data(self) -> bytes: ...
    @property
    def data_hex(self) -> str: ...

class RawProgram:
    @property
    def logical_index(self) -> int: ...
    @property
    def logical_name(self) -> str | None: ...
    @property
    def metadata_source(self) -> SourceSpan: ...
    @property
    def source(self) -> SourceSpan | None: ...
    @property
    def profile(self) -> str | None: ...
    @property
    def framing_status(self) -> str: ...
    @property
    def token_region(self) -> SourceSpan | None: ...
    @property
    def trailer(self) -> SourceSpan | None: ...
    @property
    def tokens(self) -> list[RawToken]: ...
    @property
    def opaque_regions(self) -> list[OpaqueRegion]: ...
    @property
    def diagnostics(self) -> list[ParseDiagnostic]: ...

class ParsedProject:
    @property
    def schema_version(self) -> int: ...
    @property
    def index(self) -> ProjectIndex: ...
    @property
    def semantic_status(self) -> str: ...
    @property
    def cpu_model(self) -> str | None: ...
    @property
    def execution_order(self) -> list[int] | None: ...
    @property
    def framing_complete(self) -> bool: ...
    @property
    def sources(self) -> list[SourceInfo]: ...
    @property
    def programs(self) -> list[RawProgram]: ...
    @property
    def diagnostics(self) -> list[ParseDiagnostic]: ...
    def read_source(self, source: SourceSpan) -> bytes: ...
    def to_json(self) -> str: ...

def load_project(
    path: str | PathLike[str], *, limits: ReadLimits | None = None
) -> ParsedProject: ...
def loads(data: bytes, *, limits: ReadLimits | None = None) -> ParsedProject: ...

class InstructionSpan:
    @property
    def source_id(self) -> int | None: ...
    @property
    def offset(self) -> int: ...
    @property
    def length(self) -> int: ...

class OperandValue:
    @property
    def kind(self) -> str: ...
    @property
    def device(self) -> str | None: ...
    @property
    def address(self) -> int | None: ...
    @property
    def value(self) -> int | None: ...
    @property
    def radix(self) -> int | None: ...
    @property
    def bit_width(self) -> int | None: ...

class Operand:
    @property
    def value(self) -> OperandValue: ...
    @property
    def original_text(self) -> str | None: ...
    @property
    def encoding_width_bits(self) -> int | None: ...
    @property
    def source(self) -> InstructionSpan: ...

class Instruction:
    @property
    def ordinal(self) -> int: ...
    @property
    def step(self) -> int | None: ...
    @property
    def opcode(self) -> str | None: ...
    @property
    def mnemonic(self) -> str | None: ...
    @property
    def original_mnemonic(self) -> str | None: ...
    @property
    def operands(self) -> list[Operand]: ...
    @property
    def source(self) -> InstructionSpan: ...
    @property
    def supported(self) -> bool: ...

class InstructionDiagnostic:
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def source(self) -> InstructionSpan | None: ...

class CsvRow:
    @property
    def number(self) -> int: ...
    @property
    def fields(self) -> list[str]: ...
    @property
    def source(self) -> InstructionSpan: ...
    @property
    def field_sources(self) -> list[InstructionSpan]: ...

class InstructionProgram:
    @property
    def schema_version(self) -> int: ...
    @property
    def origin(self) -> str: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def device_profile(self) -> str: ...
    @property
    def logical_name(self) -> str | None: ...
    @property
    def instructions(self) -> list[Instruction]: ...
    @property
    def diagnostics(self) -> list[InstructionDiagnostic]: ...
    @property
    def opaque_regions(self) -> list[InstructionSpan]: ...
    @property
    def csv_rows(self) -> list[CsvRow]: ...
    @property
    def complete(self) -> bool: ...
    def read_source(self, span: InstructionSpan) -> bytes: ...
    def to_json(self) -> str: ...

def decode_program(
    project: ParsedProject, program_index: int, *, device_profile: str
) -> InstructionProgram: ...
def load_csv(
    path: str, *, device_profile: str, limits: ReadLimits | None = None
) -> InstructionProgram: ...
def parse_csv_bytes(
    data: bytes, *, device_profile: str, limits: ReadLimits | None = None
) -> InstructionProgram: ...

class AnalysisOptions:
    def __init__(
        self,
        *,
        external_writes: list[str] | None = None,
        inputs_external: bool = True,
        max_instructions: int = 100_000,
        max_block_depth: int = 8,
        max_mps_depth: int = 11,
    ) -> None: ...
    @property
    def external_writes(self) -> list[str]: ...
    @property
    def inputs_external(self) -> bool: ...
    @property
    def max_instructions(self) -> int: ...
    @property
    def max_block_depth(self) -> int: ...
    @property
    def max_mps_depth(self) -> int: ...

class DeviceRef:
    @property
    def name(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def address(self) -> int: ...

class Finding:
    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def instruction(self) -> int | None: ...
    @property
    def related_instructions(self) -> list[int]: ...
    @property
    def source(self) -> InstructionSpan | None: ...

class DeviceAccess:
    @property
    def device(self) -> DeviceRef: ...
    @property
    def instruction(self) -> int: ...
    @property
    def operand(self) -> int: ...
    @property
    def mode(self) -> str: ...
    @property
    def write_kind(self) -> str | None: ...
    @property
    def source(self) -> InstructionSpan: ...

class DeviceUsage:
    @property
    def device(self) -> DeviceRef: ...
    @property
    def external_write(self) -> bool: ...
    @property
    def reads(self) -> list[int]: ...
    @property
    def writes(self) -> list[int]: ...
    @property
    def unknown(self) -> list[int]: ...

class Condition:
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def instruction(self) -> int: ...
    @property
    def inputs(self) -> list[int]: ...
    @property
    def inverted(self) -> bool: ...

class LadderOutput:
    @property
    def instruction(self) -> int: ...
    @property
    def condition(self) -> int: ...

class LadderControl:
    @property
    def instruction(self) -> int: ...
    @property
    def condition(self) -> int | None: ...

class SvgElement:
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def instruction(self) -> int: ...
    @property
    def source(self) -> InstructionSpan: ...
    @property
    def label(self) -> str: ...
    @property
    def inverted(self) -> bool: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...

class AnalysisReport:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def complete(self) -> bool: ...
    @property
    def accesses(self) -> list[DeviceAccess]: ...
    @property
    def devices(self) -> list[DeviceUsage]: ...
    @property
    def diagnostics(self) -> list[Finding]: ...
    @property
    def program(self) -> InstructionProgram: ...
    def to_json(self) -> str: ...

class LadderGraph:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def complete(self) -> bool: ...
    @property
    def conditions(self) -> list[Condition]: ...
    @property
    def outputs(self) -> list[LadderOutput]: ...
    @property
    def controls(self) -> list[LadderControl]: ...
    @property
    def processed_instructions(self) -> int: ...
    @property
    def diagnostics(self) -> list[Finding]: ...
    @property
    def program(self) -> InstructionProgram: ...
    def to_json(self) -> str: ...

class SvgDocument:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def layout(self) -> str: ...
    @property
    def complete(self) -> bool: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def elements(self) -> list[SvgElement]: ...
    @property
    def svg(self) -> str: ...
    @property
    def graph(self) -> LadderGraph: ...
    @property
    def program(self) -> InstructionProgram: ...
    def to_json(self) -> str: ...
    def to_html(self) -> str: ...
    def _repr_svg_(self) -> str: ...

class DiffHunk:
    @property
    def kind(self) -> str: ...
    @property
    def left_start(self) -> int: ...
    @property
    def left_count(self) -> int: ...
    @property
    def right_start(self) -> int: ...
    @property
    def right_count(self) -> int: ...
    @property
    def left_sources(self) -> list[InstructionSpan]: ...
    @property
    def right_sources(self) -> list[InstructionSpan]: ...

class ProgramDiff:
    @property
    def schema_version(self) -> int: ...
    @property
    def left_sha256(self) -> str: ...
    @property
    def right_sha256(self) -> str: ...
    @property
    def complete(self) -> bool: ...
    @property
    def different(self) -> bool: ...
    @property
    def opaque_changed(self) -> bool: ...
    @property
    def hunks(self) -> list[DiffHunk]: ...
    @property
    def left_program(self) -> InstructionProgram: ...
    @property
    def right_program(self) -> InstructionProgram: ...
    def to_json(self) -> str: ...

def analyze(
    program: InstructionProgram, *, options: AnalysisOptions | None = None
) -> AnalysisReport: ...
def build_ladder(
    program: InstructionProgram, *, options: AnalysisOptions | None = None
) -> LadderGraph: ...
def render_ladder(
    program: InstructionProgram,
    *,
    options: AnalysisOptions | None = None,
    max_elements: int = 20_000,
    max_output_bytes: int = 16_777_216,
) -> SvgDocument: ...
def diff_programs(
    left: InstructionProgram, right: InstructionProgram, *, max_cells: int = 1_000_000
) -> ProgramDiff: ...

class SimulationError(GxwError):
    code: str
    instruction: int | None

class SimulationLimits:
    def __init__(
        self,
        *,
        max_scans: int = 100_000,
        max_operations: int = 100_000_000,
        max_trace_values: int = 1_000_000,
        max_events: int = 100_000,
    ) -> None: ...
    @property
    def max_scans(self) -> int: ...
    @property
    def max_operations(self) -> int: ...
    @property
    def max_trace_values(self) -> int: ...
    @property
    def max_events(self) -> int: ...

class TimerState:
    @property
    def device(self) -> str: ...
    @property
    def time_base_ns(self) -> int: ...
    @property
    def evaluation(self) -> str: ...
    @property
    def retentive(self) -> bool: ...
    @property
    def preset(self) -> int | None: ...
    @property
    def value(self) -> int: ...
    @property
    def elapsed_ns(self) -> int: ...
    @property
    def phase_ns(self) -> int: ...
    @property
    def input(self) -> bool: ...
    @property
    def previous_input(self) -> bool: ...
    @property
    def done(self) -> bool: ...
    @property
    def reset_active(self) -> bool: ...

class CounterState:
    @property
    def device(self) -> str: ...
    @property
    def retentive(self) -> bool: ...
    @property
    def preset(self) -> int | None: ...
    @property
    def value(self) -> int: ...
    @property
    def input(self) -> bool: ...
    @property
    def previous_input(self) -> bool: ...
    @property
    def rising_edge(self) -> bool: ...
    @property
    def done(self) -> bool: ...
    @property
    def reset_active(self) -> bool: ...

class CompiledInstruction:
    @property
    def preset(self) -> int | None: ...
    @property
    def instruction(self) -> int: ...
    @property
    def opcode(self) -> str: ...
    @property
    def device(self) -> DeviceRef | None: ...
    @property
    def source(self) -> InstructionSpan: ...

class CompiledProgram:
    @property
    def schema_version(self) -> int: ...
    @property
    def profile(self) -> str: ...
    @property
    def execution_scope(self) -> str: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def instructions(self) -> list[CompiledInstruction]: ...
    @property
    def devices(self) -> list[DeviceRef]: ...
    @property
    def program(self) -> InstructionProgram: ...
    def to_json(self) -> str: ...

class InstructionEvent:
    @property
    def time_ns(self) -> int: ...
    @property
    def timer(self) -> TimerState | None: ...
    @property
    def counter(self) -> CounterState | None: ...
    @property
    def instruction(self) -> int: ...
    @property
    def opcode(self) -> str: ...
    @property
    def device(self) -> DeviceRef | None: ...
    @property
    def source(self) -> InstructionSpan: ...
    @property
    def accumulator(self) -> bool | None: ...
    @property
    def read_value(self) -> bool | None: ...
    @property
    def write_value(self) -> bool | None: ...
    @property
    def external_output(self) -> bool | None: ...

class ScanSnapshot:
    @property
    def timer_phase_ns(self) -> int: ...
    @property
    def timing_model(self) -> str: ...
    @property
    def retention_policy(self) -> str: ...
    @property
    def running(self) -> bool: ...
    @property
    def timers(self) -> dict[str, TimerState]: ...
    @property
    def counters(self) -> dict[str, CounterState]: ...
    def timer(self, device: str) -> TimerState: ...
    def counter(self, device: str) -> CounterState: ...
    @property
    def profile(self) -> str: ...
    @property
    def execution_scope(self) -> str: ...
    @property
    def scan_period_ns(self) -> int: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def scan(self) -> int: ...
    @property
    def time_ns(self) -> int: ...
    @property
    def devices(self) -> dict[str, bool]: ...
    @property
    def outputs(self) -> dict[str, bool]: ...
    @property
    def instruction_trace(self) -> list[InstructionEvent]: ...
    @property
    def compiled(self) -> CompiledProgram: ...
    def to_json(self) -> str: ...
    def get(self, device: str) -> bool: ...
    def output(self, device: str) -> bool: ...

class ScanSample:
    @property
    def timers(self) -> dict[str, TimerState]: ...
    @property
    def counters(self) -> dict[str, CounterState]: ...
    @property
    def scan(self) -> int: ...
    @property
    def time_ns(self) -> int: ...
    @property
    def values(self) -> list[bool]: ...

class ScanTrace:
    @property
    def timer_phase_ns(self) -> int: ...
    @property
    def timing_model(self) -> str: ...
    @property
    def retention_policy(self) -> str: ...
    @property
    def profile(self) -> str: ...
    @property
    def execution_scope(self) -> str: ...
    @property
    def scan_period_ns(self) -> int: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def start_scan(self) -> int: ...
    @property
    def requested_scans(self) -> int: ...
    @property
    def completed_scans(self) -> int: ...
    @property
    def interrupted(self) -> bool: ...
    @property
    def watch(self) -> list[str]: ...
    @property
    def samples(self) -> list[ScanSample]: ...
    @property
    def final_snapshot(self) -> ScanSnapshot: ...
    def to_json(self) -> str: ...

class Simulator:
    @property
    def timer_phase_ns(self) -> int: ...
    @property
    def running(self) -> bool: ...
    def set_scan_period_ns(self, period_ns: int) -> None: ...
    def stop(self) -> None: ...
    def start(self) -> None: ...
    def advance_stopped(self, elapsed_ns: int) -> None: ...
    @property
    def compiled(self) -> CompiledProgram: ...
    @property
    def scan_period_ns(self) -> int: ...
    @property
    def busy(self) -> bool: ...
    @property
    def scan_count(self) -> int: ...
    @property
    def time_ns(self) -> int: ...
    def __init__(
        self,
        compiled: CompiledProgram,
        *,
        scan_period_ns: int,
        initial_state: dict[str, bool] | None = None,
        limits: SimulationLimits | None = None,
        timer_phase_ns: int = 0,
    ) -> None: ...
    def set_inputs(self, values: dict[str, bool]) -> None: ...
    def set_devices(self, values: dict[str, bool]) -> None: ...
    def reset(self, *, initial_state: dict[str, bool] | None = None) -> None: ...
    def snapshot(self) -> ScanSnapshot: ...
    def step(self, *, trace_instructions: bool = False) -> ScanSnapshot: ...
    def run(self, scans: int, *, watch: list[str] | None = None) -> ScanTrace: ...

def compile_program(
    program: InstructionProgram, *, profile: str, max_instructions: int = 100_000
) -> CompiledProgram: ...

class StructuredLimits:
    def __init__(
        self,
        *,
        max_blocks: int = 4096,
        max_records: int = 100_000,
        max_ports: int = 200_000,
        max_string_units: int = 65_536,
        max_declarations: int = 65_536,
        max_connection_checks: int = 5_000_000,
    ) -> None: ...
    @property
    def max_blocks(self) -> int: ...
    @property
    def max_records(self) -> int: ...
    @property
    def max_ports(self) -> int: ...
    @property
    def max_string_units(self) -> int: ...
    @property
    def max_declarations(self) -> int: ...
    @property
    def max_connection_checks(self) -> int: ...

class StructuredProgram:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def logical_name(self) -> str | None: ...
    @property
    def logical_index(self) -> int: ...
    @property
    def profile(self) -> str: ...
    @property
    def source(self) -> SourceSpan: ...
    @property
    def header(self) -> SourceSpan: ...
    @property
    def trailer(self) -> SourceSpan: ...
    @property
    def structure_complete(self) -> bool: ...
    @property
    def semantic_status(self) -> str: ...
    @property
    def blocks(self) -> list[StructuredBlock]: ...
    @property
    def diagnostics(self) -> list[ParseDiagnostic]: ...
    def to_json(self) -> str: ...

class StructuredBlock:
    @property
    def index(self) -> int: ...
    @property
    def source(self) -> SourceSpan: ...
    @property
    def header(self) -> SourceSpan: ...
    @property
    def canvas_height(self) -> int: ...
    @property
    def record_count(self) -> int: ...
    @property
    def connectivity_complete(self) -> bool: ...
    @property
    def nodes(self) -> list[StructuredNode]: ...
    @property
    def wires(self) -> list[StructuredWire]: ...
    @property
    def nets(self) -> list[StructuredNet]: ...
    @property
    def opaque_records(self) -> list[OpaqueRegion]: ...

class StructuredNode:
    @property
    def ordinal(self) -> int: ...
    @property
    def kind_code(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def symbol(self) -> str: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def object_flag(self) -> int | None: ...
    @property
    def reserved(self) -> int | None: ...
    @property
    def bounds(self) -> list[int]: ...
    @property
    def source(self) -> SourceSpan: ...
    @property
    def ports(self) -> list[StructuredPort]: ...

class StructuredPort:
    @property
    def index(self) -> int: ...
    @property
    def kind_code(self) -> int: ...
    @property
    def local(self) -> tuple[int, int]: ...
    @property
    def position(self) -> tuple[int, int]: ...
    @property
    def source(self) -> SourceSpan: ...

class StructuredWire:
    @property
    def ordinal(self) -> int: ...
    @property
    def start(self) -> tuple[int, int]: ...
    @property
    def end(self) -> tuple[int, int]: ...
    @property
    def flags(self) -> list[int]: ...
    @property
    def suffix(self) -> int: ...
    @property
    def source(self) -> SourceSpan: ...

class StructuredNet:
    @property
    def index(self) -> int: ...
    @property
    def wires(self) -> list[int]: ...
    @property
    def ports(self) -> list[tuple[int, int]]: ...

class DeclarationTable:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def logical_index(self) -> int: ...
    @property
    def logical_name(self) -> str: ...
    @property
    def scope(self) -> str: ...
    @property
    def owner_name(self) -> str | None: ...
    @property
    def source(self) -> SourceSpan: ...
    @property
    def header(self) -> SourceSpan: ...
    @property
    def trailer(self) -> SourceSpan: ...
    @property
    def structure_complete(self) -> bool: ...
    @property
    def rows(self) -> list[LabelDeclaration]: ...
    @property
    def diagnostics(self) -> list[ParseDiagnostic]: ...
    def to_json(self) -> str: ...

class LabelDeclaration:
    @property
    def ordinal(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def data_type(self) -> str: ...
    @property
    def class_code(self) -> int: ...
    @property
    def device(self) -> str: ...
    @property
    def iec_address(self) -> str: ...
    @property
    def unknown_u32(self) -> int: ...
    @property
    def initial_value(self) -> str: ...
    @property
    def unknown_text(self) -> str: ...
    @property
    def record_id(self) -> int: ...
    @property
    def comment(self) -> str: ...
    @property
    def array_marker(self) -> int: ...
    @property
    def type_code(self) -> int: ...
    @property
    def type_reference(self) -> str: ...
    @property
    def source(self) -> SourceSpan: ...

class StructuredSvgDocument:
    @property
    def schema_version(self) -> int: ...
    @property
    def source_sha256(self) -> str: ...
    @property
    def layout(self) -> str: ...
    @property
    def structure_complete(self) -> bool: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def svg(self) -> str: ...
    @property
    def elements(self) -> list[StructuredSvgElement]: ...
    def to_json(self) -> str: ...
    def to_html(self) -> str: ...
    def _repr_svg_(self) -> str: ...

class StructuredSvgElement:
    @property
    def id(self) -> str: ...
    @property
    def block(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def label(self) -> str: ...
    @property
    def source(self) -> SourceSpan: ...

def decode_structured(
    project: ParsedProject, program_index: int, *, limits: StructuredLimits | None = None
) -> StructuredProgram: ...
def decode_declarations(
    project: ParsedProject, logical_index: int, *, limits: StructuredLimits | None = None
) -> DeclarationTable: ...
def decode_ir(
    project: ParsedProject,
    program_index: int,
    *,
    device_profile: str,
    limits: StructuredLimits | None = None,
) -> InstructionProgram | StructuredProgram: ...
def render_structured(
    program: StructuredProgram, *, max_elements: int = 20_000, max_output_bytes: int = 16_777_216
) -> StructuredSvgDocument: ...

class DeviceAddress:
    @property
    def family(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def address(self) -> int: ...
    @property
    def radix(self) -> int: ...
    @property
    def canonical(self) -> str: ...
    @property
    def range_status(self) -> str: ...

def parse_device_address(text: str, *, family: str) -> DeviceAddress: ...
