[package]
name = "gxw-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Python bindings for gxw-core"
publish = false

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
gxw-core.workspace = true
pyo3.workspace = true
